In [4]:
import tensorflow as tf
from tensorflow import keras
from keras import models , layers 
import numpy as np
import warnings 
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt

1  Implement a basic convolution operation using a filter and a 5x5 image (matrix)?

In [10]:
#define a image 
img = np.random.random((3,32,32))

convolution_layer = layers.Convolution2D(1,kernel_size= 5 , input_shape = (32,32,3))
img = img.reshape((1,32,32,3))
y=convolution_layer(img)
print(y.shape)

(1, 28, 28, 1)


2  Implement max pooling on a 4x4 feature map with a 2x2 window ?

In [18]:
#define a feature map
f_map = np.random.random((64,4,4))
max_pooling_layer = layers.MaxPooling2D(pool_size=(2,2))
f_map = f_map.reshape(1,4,4,64)
y = max_pooling_layer(f_map)
print(y.shape)

(1, 2, 2, 64)


3 Implement the ReLU activation function on a feature map?

In [24]:


#define a feature map
f_map = np.random.normal(size=(6,3,3))
#relu layer 
relu_layer = layers.ReLU()
print(f_map)
print(relu_layer(f_map))

[[[ 0.2890494   1.16238235  0.12546722]
  [-1.0359845   0.40987132  0.91501898]
  [ 0.40863406  0.92960863 -0.69482912]]

 [[-1.26055932  1.02107738 -1.97035624]
  [-1.53995769  0.64595526  0.00442906]
  [-1.47277577 -0.60133354 -0.97365795]]

 [[-0.24715361  0.62386059 -1.00146711]
  [-1.39907439 -2.32071358 -0.22579261]
  [ 0.4631491   0.35764287 -0.29402569]]

 [[-0.36919708 -0.73917952 -0.30139424]
  [-0.18463813  0.30357667  0.91218524]
  [ 0.03521278 -0.94710703  0.52532582]]

 [[-0.04798391 -0.70376729  0.06187429]
  [-0.61446617  0.68383127 -1.14928249]
  [-0.05894633 -1.94165434 -0.49113103]]

 [[-1.05958245  0.26396812 -0.8181537 ]
  [-1.13094771 -0.60065998  0.90660433]
  [-0.03166227 -0.23650932  0.08067076]]]
tf.Tensor(
[[[0.28904942 1.1623824  0.12546721]
  [0.         0.4098713  0.915019  ]
  [0.40863407 0.92960864 0.        ]]

 [[0.         1.0210774  0.        ]
  [0.         0.64595526 0.00442906]
  [0.         0.         0.        ]]

 [[0.         0.6238606  0.    

4 Create a simple CNN model with one convolutional layer and a fully connected layer, using random data ?

In [28]:
data = np.random.random(size=(1,32,32,3))
model = layers.Conv2D(10 ,kernel_size=(3,3) , activation="relu")(data)
model = layers.Dense(5 , activation="sigmoid")(model)
print(model.shape)

(1, 30, 30, 5)


5 Generate a synthetic dataset using random noise and train a simple CNN model on it ?

In [74]:

img = np.random.random((3,32,32))
model = models.Sequential([
    layers.Conv1D(10,kernel_size= 2 , activation= "relu" , input_shape = (5,5)) , 
    layers.Dense(4, activation="sigmoid"),
    layers.Dense(1,activation= "softmax")
])

In [75]:
data = np.random.randint(low=-9 , high= 9,size=(10,5,5))


In [76]:
label= [np.sum(x) for x in data]
data  = data/100
noise = np.random.normal(size=(10,5,5)) 
noise_data = data + noise

In [77]:
label = np.array(label)

In [78]:
noise_data

array([[[ 0.48226377,  0.43089261, -1.12197903, -0.02346228,
          0.50242265],
        [-0.59869744,  0.7288033 ,  0.04131725,  1.1030349 ,
          1.25365864],
        [-0.19597335, -0.59234712,  0.47042   ,  0.51593013,
          1.75928157],
        [ 0.56124385, -1.96779363, -0.32273103,  1.58849115,
          0.21369911],
        [ 1.51976053, -0.600953  , -1.8033547 ,  0.39899776,
          0.18018444]],

       [[ 1.04425834, -1.76778603, -0.08873038, -0.34618347,
          0.99994763],
        [-0.71463219, -1.31748026,  0.55479446, -0.35449664,
         -0.1750159 ],
        [ 0.51754196, -2.46807414,  1.90268233,  0.1817386 ,
         -0.15436164],
        [ 1.10302096, -0.80144639, -2.04620289, -1.30810448,
         -0.56779826],
        [ 0.50335233, -0.58359357, -1.01670948, -1.61107636,
          0.76276039]],

       [[-0.87674074, -0.03029282, -0.21041701, -1.09514695,
         -0.05871135],
        [-0.8524443 , -1.31473107,  0.94019795,  0.26925075,
          1

In [79]:
model.compile(optimizer= "adam" , loss="mse" , metrics=["accuracy"])

In [80]:
model.fit(x=noise_data , y = label , epochs= 4, verbose= 1 , batch_size= 2 , validation_split=0.5)

Epoch 1/4
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - accuracy: 0.0000e+00 - loss: 739.6250 - val_accuracy: 0.0000e+00 - val_loss: 1044.2000
Epoch 2/4
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 797.4375 - val_accuracy: 0.0000e+00 - val_loss: 1044.2000
Epoch 3/4
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.0000e+00 - loss: 845.2500 - val_accuracy: 0.0000e+00 - val_loss: 1044.2000
Epoch 4/4
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0000e+00 - loss: 724.3125 - val_accuracy: 0.0000e+00 - val_loss: 1044.2000


6 Create a simple CNN using Keras with one convolution layer and a max-pooling layer?

In [84]:
model = models.Sequential([
    layers.Conv2D(32, kernel_size=(3,3) , activation= "relu" , input_shape = (32,32,3)),
    layers.MaxPool2D(pool_size=(2,2))
])
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_14 (Conv2D)              │ (None, 30, 30, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 15, 15, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 896 (3.50 KB)

 Trainable params: 896 (3.50 KB)

 Non-trainable params: 0 (0.00 B)

7 Write a code to add a fully connected layer after the convolution and max-pooling layers in a CNN?

In [85]:
model = models.Sequential([
    layers.Conv2D(32, kernel_size=(3,3) , activation= "relu" , input_shape = (32,32,3)),
    layers.MaxPool2D(pool_size=(2,2)),
    layers.Dense(10 , activation= "sigmoid")
])
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_15 (Conv2D)              │ (None, 30, 30, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_10 (MaxPooling2D) │ (None, 15, 15, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 15, 15, 10)     │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,226 (4.79 KB)

 Trainable params: 1,226 (4.79 KB)

 Non-trainable params: 0 (0.00 B)

8 Write a code to add  batch normalization to a simple CNN model?

In [86]:
model = models.Sequential([
    layers.Conv2D(32, kernel_size=(3,3) , activation= "relu" , input_shape = (32,32,3)),
    layers.BatchNormalization(),
    layers.MaxPool2D(pool_size=(2,2)),
    layers.Dense(10 , activation= "sigmoid")
])
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_16 (Conv2D)              │ (None, 30, 30, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 30, 30, 32)     │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_11 (MaxPooling2D) │ (None, 15, 15, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 15, 15, 10)     │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,354 (5.29 KB)

 Trainable params: 1,290 (5.04 KB)

 Non-trainable params: 64 (256.00 B)

9 Write a code to add dropout regularization to a simple CNN mode?

In [89]:
model = models.Sequential([
    layers.Conv2D(32, kernel_size=(3,3) , activation= "relu" , input_shape = (32,32,3)),
    layers.MaxPool2D(pool_size=(2,2)),
    layers.Dense(20 , activation= "relu"),
    layers.Dropout(rate= 0.4),
    layers.Dense(5 , activation= "sigmoid")
])
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_18 (Conv2D)              │ (None, 30, 30, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 15, 15, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 15, 15, 20)     │           660 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 15, 15, 20)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 15, 15, 5)      │           105 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,661 (6.49 KB)

 Trainable params: 1,661 (6.49 KB)

 Non-trainable params: 0 (0.00 B)

10 Write a code to print the architecture of the VGG16 model in Keras ?

In [96]:
vgg16 = keras.applications.VGG16()
vgg16.summary()

Model: "vgg16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_8 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv1 (Conv2D)           │ (None, 224, 224, 64)   │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv2 (Conv2D)           │ (None, 224, 224, 64)   │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_pool (MaxPooling2D)      │ (None, 112, 112, 64)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv1 (Conv2D)           │ (None, 112, 112, 128)  │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv2 (Conv2D)           │ (None, 112, 112, 128)  │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_pool (MaxPooling2D)      │ (None, 56, 56, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv1 (Conv2D)           │ (None, 56, 56, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv2 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv3 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_pool (MaxPooling2D)      │ (None, 28, 28, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv1 (Conv2D)           │ (None, 28, 28, 512)    │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv2 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv3 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_pool (MaxPooling2D)      │ (None, 14, 14, 512)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv1 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv2 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv3 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_pool (MaxPooling2D)      │ (None, 7, 7, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc1 (Dense)                     │ (None, 4096)           │   102,764,544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc2 (Dense)                     │ (None, 4096)           │    16,781,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ predictions (Dense)             │ (None, 1000)           │     4,097,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 138,357,544 (527.79 MB)

 Trainable params: 138,357,544 (527.79 MB)

 Non-trainable params: 0 (0.00 B)

11 Write a code to plot the accuracy and loss graphs after training a CNN model?

In [99]:
def plot_loss_accuracy(history):
    plt.plot(history.history['acc'])
    plt.plot(history.history['val_acc'])
    plt.xlabel('epoch')
    plt.ylabel('accuracy')
    plt.show()


# history  = model.fit (x, y ,....)
#for plot plot_loss_accuracy(history)

Write a code to print the architecture of the ResNet50 model in Keras

In [ ]:
resnet50 = keras.applications.ResNet50()
print(resnet50.summry)

Write a code to train a basic CNN model and print the training loss and accuracy after each epoch

In [5]:
import datetime
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir = log_dir , histogram_freq = 1)
#model.fit(x = x_train, y = y_train, ..........., callbacks = [tessorboard_callback])